name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Specify the Ruby version you need for your project

      # Install dependencies (Jekyll)
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Build the site with Jekyll
      - name: Build Jekyll site
        run: jekyll build

      # Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BERGERJ_WEBSERVER }}
          channelId: live
          projectId: bergerj-webserver